#!/bin/bash

# Building and Install remora: a performance monitor tool from TACC:

# This file exists in the mkmod examples directory. If mkmod is accessible:
# the directory path is:  echo $(dirname `which mkmod`)/../examples/remora


#  INSTALLATION:

#    a.) cd to a build/install directory
#        (e.g. mkdir $HOME/apps; cd $HOME/apps) @TACC maybe use $WORK for $HOME


#    b.) get TACC distro:  git clone https://github.com/tacc/remora
#    c.) cd to remora:     cd remora
#    d.) INSTALL:          ./install.sh

#    For mkmod
#    e.) Set 3 variables required by mkmod.
#    f.) Execute the mkmod_remora script-- executes mkmod.


# Get the remora performance monitor from TACC:

         git clone https://github.com/tacc/remora

# Build
         cd remora
         ./install.sh

         echo ""
         echo " DON'T WORRY ABOUT ABOVE EXPORT COMMANDS--mkmod will handle those."
         echo ""
         echo " Set these 3 primary variables required by mkmod."
         echo " (You can copy and paste all three at once onto the command line.)"
         echo ""
         echo "    export TOPDIR=`pwd`"
         echo "    export    VER=`grep -Po 'VERSION=\K[0-9.]*' install.sh`"
         echo "    export   NAME=remora"
         echo ""
         echo " Next, execute the commands in  the mkmod_remora file-- from any directory."

