#!/bin/bash

# Real World Example with mkmod
# Make sure you have made a modulefile for mkmod and have loaded it.
# (See docs/INSTALL)
#  

# Features:  uses module help-message file (provided)
#            NOTE:  it uses the $VER variable inside module_help_message

# Get the remora performance monitor from TACC:

         git clone https://github.com/tacc/remora

# Build
         cd remora
         ./install.sh

#   Get the Version number, inside install.sh look for VERSION=x.y.z or just execute
#   this grep and replace with the correct value below.
        grep -Po 'VERSION=\K[0-9.]*' install.sh

         export VER=1.8.1
         export NAME=remora
         export TOPDIR=`pwd`

         export PREFIX=""
         export HELP_FILE=$MY_MKMOD_EXM/remora/modules_help

         export ENV1="REMORA_BIN=$TOPDIR/bin"
         export ENV2="REMORA_VERBOSE=0"
         export ENV3="REMORA_MODE=FULL"
         export ENV4="REMORA_PERIOD=10"

         mkmod

#HELP_FILE taken from TACC's remora module.
#Note: Possibly remora developers will support mkmod and will
       provide a modules_help message file  in their distro.
       provide a modules_whatis info file in their distro.
