#!/bin/bash

# You can just execute this file, or cut and past commands.
#
# Real World Example with mkmod
# Make sure you have made a modulefile for mkmod and have loaded it.

# Features:  uses module help-message file (provided)
#            NOTE:  it uses the $VER variable inside modules_help

#   Instructions from build_remora install specify (using cut and paste on cmd line)
#   setting the NAME, VER and TOPDIR environment variables for this script.

                                   #Set the directory for modules_help file.
export MKMOD_HELP=$(dirname `which mkmod`)/../examples/remora/modules_help
                                   #If modules_help were in the remora directory
                                   #mkmod would find and use it automatically.

         export PREFIX=""                   # forget using my_remora-- just use "remora"
                                            # for modulefile name
         export HELP_FILE=$MKMOD_HELP       # help file to include append to module help msg

         export ENV1="REMORA_BIN=$TOPDIR/bin"   # variable-- required by remora
         export ENV2="REMORA_VERBOSE=0"         # optional variables set in modulefile
         export ENV3="REMORA_MODE=FULL"         #   "
         export ENV4="REMORA_PERIOD=10"         #   "

         mkmod

#HELP_FILE taken from TACC's remora module.
#Note: Possibly remora developers will support mkmod and will
#      provide a modules_help message file in their distro.
#todo: provide a modules_whatis info file in their distro.
