#!/bin/bash

# Features:  using whatis
#            APP Environment Variable  (ENV1)
#            module "conflict" command (CMD1)
#            user-defined prepend to MANPATH (manpath_list)
#            user-defined compiler/mpi prereqs (COMPILER_PREREQ, MPI_PREREQ)

DIR=/opt/apps/intel18/impi18_0/boost/1.66

            NAME=boost
             VER=1.66
          TOPDIR=$DIR

   export NAME VER TOPDIR

export \
   WHATIS="    Name: boost "
   WHATIS+=" @ Version: 1.66"
   WHATIS+=" @ Category Lmod/Modulefiles" 
   WHATIS+=" @ Keywords: System, Library, C++ "
   WHATIS+=" @ URL: http://www.boost.org"
   WHATIS+=" @ Description: Boost provides free peer-reviewed portable C++ source libraries."

   
   export  ENV1="BOOST_ROOT=$DIR"
   export  CMD1="conflict(\"boost\",\"boost-mpi\")"
   export  manpath_list="$DIR/share/man"
   export  COMPILER_PREREQ="intel/18.0.0"
   export  MPI_PREREQ="impi/18.0.0"

./mkmod

